SCHOOL_YEAR  = "2017".freeze
AWC_GRADES = ['4', '5', '6'].freeze
TRANSITION_GRADES = ['K0', 'K1', 'K2', '6', '9'].freeze
NON_TRANSITION_GRADES = ['1', '2', '3', '4', '5', '7', '8', '10', '11', '12'].freeze
SURROUND_CARE_GRADES 	= ['K0', 'K1', 'K2', '1', '2', '3'].freeze
UPPER_GRADES = ['6', '7', '8', '9', '10', '11', '12'].freeze
SCHOOL_SHOWCASE_DATE = "Dec 3".freeze
HIGHSCHOOL_SHOWCASE_DATE = "Dec 1".freeze
SCHOOL_PRE_REG_DATE = "Dec".freeze
REG_ALL_GRADE = "Feb 8".freeze
REG_ASSIGNMENT_MAILED = "Mar - Jun".freeze
REG_TRANSITION_GRADE = "Jan 3 - Feb 3".freeze
REG_TRANSITION_GRADE_LASTNAME_AI = "Jan 3-6".freeze
REG_TRANSITION_GRADE_LASTNAME_JQ = "Jan 9-13".freeze
REG_TRANSITION_GRADE_LASTNAME_RZ = "Jan 16-20".freeze
REG_TRANSITION_GRADE_LASTNAME_ALL = "Jan 23-27".freeze
FIRST_DAY_OF_SCHOOL = "Sep 7".freeze
SCHOOL_YEAR_CONTEXT = "2017-2018".freeze
SERVICE_CLIENT_CODE = "Discover".freeze

